"""Minimal type stubs for asyncpg — covers only APIs used by AgentStudio."""

from __future__ import annotations

from typing import Any, Awaitable, Sequence


class Connection:
    async def execute(self, query: str, *args: Any) -> str: ...
    async def executemany(self, query: str, args: Sequence[Sequence[Any]]) -> None: ...
    async def fetch(self, query: str, *args: Any) -> list[Any]: ...
    async def fetchval(self, query: str, *args: Any) -> Any: ...
    async def close(self) -> None: ...


async def connect(dsn: str, *, timeout: float | None = None) -> Connection: ...
